//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopersArticle.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ObjectID { get; set; }
        public string CommentContent { get; set; }
        public int ArticleId { get; set; }
        public int WriterId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public int IsModified { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Developer Developer { get; set; }
    }
}
